services:
  backend:
    build: ./server
    container_name: tekstructers-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./client
    container_name: tekstructers-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
